config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#top"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "signup", to: "users#new"
  resources :users, only: [:show, :create, :edit, :update]
    
  resources :posts
  resources :likes, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email.downcase! }
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence:true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :profile, length: { maximum: 200}
  mount_uploader :profile_image, ImageUploader
  has_secure_password
  
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def like(a_post)
    self.likes.find_or_create_by(post_id: a_post.id)
  end
  
  def remove_like(a_post)
    like = self.likes.find_by(post_id: a_post.id)
    like.destroy if like
  end
  
  def like?(a_post)
    self.like_posts.include?(a_post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper

  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def not_logged_in
    if logged_in?
      redirect_to posts_path
    end
  end
  
  def counts_user(user)
    @count_posts = user.posts.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_like_posts = user.like_posts.count
  end
  
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @post = Post.find(params[:post_id])
    current_user.like(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    current_user.remove_like(@post)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [ :edit, :update, :destroy ]
  
  def index
    @posts = Post.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to posts_path
    else
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      flash[:success] = "投稿を編集しました"
      redirect_to posts_path
    else
      flash.now[:danger] = "投稿を編集できませんでした"
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to posts_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:content, :image)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to posts_path
    end
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    @user = User.find(params[:follow_id])
    current_user.follow(@user)
    @followers = @user.followers.page(params[:page])
  end
  
  def destroy
    @user = User.find(params[:follow_id])
    current_user.unfollow(@user)
    @followers = @user.followers.page(params[:page])
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :not_logged_in, only: [:new, :create]
  
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to posts_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :not_logged_in
  

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  before_action :not_logged_in, only: [:new, :create]

 
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc).page(params[:page])
    @followings = @user.followings.page(params[:page])
    @followers = @user.followers.page(params[:page])
    @like_posts = @user.like_posts.page(params[:page])
    counts_user(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if current_user == @user
      image = params[:profile_image]
      if image
        #データベースに保存するファイル名はユーザーのid.jpgとする
        @user.profile_image = "#{@user.id}.jpg"
        File.binwrite("public/user_images/#{@user.profile_image}",image.read)
      end
      if @user.update(user_params)
        flash[:success] = "ユーザ情報を編集しました"
        redirect_to user_path
      else
        flash.now[:danger] = "ユーザ情報を編集できませんでした"
        render :edit
      end
    else
      redirect_to posts_path
    end
  end
    
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-secondary">
    <a class="navbar-brand" href="/posts">
      <i class="fas fa-feather-alt"></i>
      Dailyposts
    </a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav " >
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to new_post_path, class: 'nav-link' do %>
              <i class="fab fa-envira"></i>
              投稿する
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <i class="fas fa-user"></i>
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item">
                <%= link_to user_path(current_user) do %>
                  <i class="fas fa-portrait"></i>
                  プロフィール
                <% end %>
              </li>
              <li class="dropdown-item">
                <%= link_to edit_user_path(current_user) do %>
                  <i class="far fa-edit"></i>
                  プロフィール編集
                <% end %>
              </li>
              <li class="dropdown-item">
                <%= link_to logout_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i>
                  ログアウト
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to signup_path, class: 'nav-link' do %>
              <i class="fas fa-user-plus"></i>
              登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to login_path, class: 'nav-link' do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dailyposts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= stylesheet_link_tag "layout" %>
    <%= yield :css %>
    <%= javascript_include_tag 'application' %>
    
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  </body>
</html>

app/views/likes/_like.html.erb
<% if current_user.like?(post) %>
  <%= form_with(model: current_user.likes.find_by(post_id: post.id), remote: true, method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-outline-danger" do %>
      <i class="fas fa-thumbs-down"></i>
      unlike
    <% end %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.likes.build, remote: true) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= button_tag :type => "submit", :class =>"btn btn-outline-primary" do %>
      <i class="fas fa-thumbs-up"></i>
      like
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-<%= @post.id %>").html("<%= escape_javascript(render "like",  post: @post)%>");

app/views/likes/destroy.js.erb
$("#like-<%= @post.id %>").html("<%= escape_javascript(render "like",  post: @post)%>");

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: post, local: true) do |f| %>
      <% if post.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= f.label :content, "投稿内容" %>
        <%= f.text_field :content, class:"form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, "投稿画像" %>
        <%= f.file_field :image, class:"form-control-file" %>
      </div>
      
      
      <%= button_tag :type => "submit", :class =>"btn btn-primary" do %>
        <i class="fab fa-envira"></i>
        投稿
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/_posts.html.erb
<ul class="list-unstyled ">
  <% posts.each do |post| %>
    <li class="media mb-3 border-top" style="padding: 10px;">
      <div class="media-body">
        <div>
          <%= link_to user_path(post.user),:style => "color: black;" do %>
            <% if post.user.profile_image? %>
              <%= image_tag post.user.profile_image.url(:thumb)  %>
            <% else %>
              <img class="rounded img-fluid" src="/assets/default.png" alt="" width="30" height="30 "%>
            <% end %>
            <%= post.user.name %>
          <% end %>
          <span class="text-muted">posted at <%= post.created_at.to_s(:datetime_jp) %></span>
        </div>
        <div style="margin-top: 10px;">
          <p><%= link_to post.content, post, :style => "color: black;" %></p>
        </div>
        <div>
          <p><%= image_tag post.image.url if post.image?  %></p>
        </div>
        <div id="like-<%= post.id %>">
          <%= render "likes/like", post: post %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<%= render "form" , post: @post %>

app/views/posts/index.html.erb
<div class="col-md-6 offset-md-2">
  <h1><i class="fas fa-seedling"></i> <span style="letter-spacing: 5pt;"> 投稿一覧</span></h1>
  <%= render 'posts', posts: @posts %>
</div>

app/views/posts/new.html.erb
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1>投稿詳細ページ</h1>

<table class="table table-striped">
  <tr>
    <th>ユーザ</th>
    <td><%= @post.user.name %></td>
  </tr>
  <tr>
    <th>投稿内容</th>
    <td><%= @post.content %></td>
  </tr>
  <% if @post.image? %> 
    <tr>
      <th>投稿画像</th>
      <td><%= image_tag @post.image.url %></td>
    </tr>
  <% end %>
</table>
<% if current_user == @post.user %>
  <%= link_to edit_post_path(@post), class: "btn btn-light" do %>
    <i class="far fa-edit"></i>
    編集
  <% end %>
  <%= link_to @post, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-outline-danger" do %>
    <i class="fas fa-trash"></i>
    削除
  <% end %>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), remote: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= button_tag :type => "submit", :class =>"btn btn-outline-danger btn-block" do %>
       <i class="fas fa-user-slash"></i>
       unfollow
      <% end %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, remote: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= button_tag :type => "submit", :class =>"btn btn-outline-primary btn-block" do %>
       <i class="fas fa-user"></i>
       follow
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#follow_button").html("<%= escape_javascript(render "follow_button",  user: @user)%>");
$(".follower-counts").html("<%= @user.followers.count %>");

app/views/relationships/destroy.js.erb
$("#follow_button").html("<%= escape_javascript(render "follow_button",  user: @user)%>");
$(".follower-counts").html("<%= @user.followers.count %>");

app/views/toppages/top.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag "top" %>
<% end %>
<div class="wrapper">
  <div class="bk-rgba">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-black font-weight-bold">Dailyposts</h1>
        <hr class="divider my-4" />
      </div>
      <div class="col-lg-8 align-self-baseline">
        <p class="text-white-75 font-weight-light mb-5">DailyPostでは、あなたの日常を投稿できます。他の人の投稿も見ることができます。今すぐ始めよう！</p>
        <div class="row">
          <div class="offset-3 col-3">
            <%= link_to "新規登録", signup_path, class:"btn btn-primary" %>
          </div>
          <div class="col-3">
            <%= link_to "ログイン", login_path, class:"btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_items.html.erb
<ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item">
    <a href="#posts" class="nav-link active" data-toggle="tab">
      posts<span class="badge badge-secondary"><%= @count_posts %></span>
    </a>
  </li>
  <li class="nav-item">
    <a href="#follows" class="nav-link" data-toggle="tab">
      follows<span class="badge badge-secondary"><%= @count_followings %></span>
    </a>
  </li>
  <li class="nav-item">
    <a href="#followers" class="nav-link" data-toggle="tab">
      followers<span class="badge badge-secondary follower-counts"><%= @count_followers %></span>
    </a>
  </li>
  <li class="nav-item">
    <a href="#likes" class="nav-link" data-toggle="tab">
     likes<span class="badge badge-secondary"><%= @count_like_posts %></span>
    </a>
  </li>
</ul>

<div class="tab-content">
  <div id="posts" class="tab-pane active">
    <%= render 'posts/posts', posts: @posts %>
  </div>
  <div id="follows" class="tab-pane">
    <%= render 'users', users: @followings %>
  </div>
  <div id="followers" class="tab-pane">
    <%= render 'users', users: @followers %>
  </div>
  <div id="likes" class="tab-pane">
    <%= render 'posts/posts', posts: @like_posts %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="card text-center">
  <div class="card-header">
   <h3 class="card-title"><%= user.name %></h3>
  </div>
  <div class="card-image">
    <figure class="image">
      <% if user.profile_image? %>
        <img class="rounded img-fluid " src= "<%= user.profile_image.url %>" alt="" %>
      <% else %>
        <img class="rounded img-fluid" src="/assets/default.png" alt="" %>
      <% end %>
    </figure>
  </div>
  <hr>
  <div class="pb-2" style="font-size:14px; font-weight:bold;">自己紹介</div>
  <%= user.profile %>
</div>

<div id="follow_button">
  <%= render 'relationships/follow_button', user: user %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>ユーザ情報</h1>
</div>


<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile, '自己紹介' %>
        <%= f.text_area :profile, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile_image, 'プロフィール画像' %>
        <%= f.file_field :profile_image, class: 'form-control-file' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block mt-5' %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザ登録</h1>
</div>


<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= render "profile", user: @user %>
  </div>
  <div class="col-sm-8">
    <%= render "items", user: @user %>
  </div>
</div>